"""initial schema

Revision ID: bd1bb7189838
Revises: 
Create Date: 2026-07-30 08:14:55.170715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1bb7189838'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('model_series', sa.String(length=100), nullable=False),
    sa.Column('rack_units', sa.Integer(), nullable=True),
    sa.Column('part_number', sa.String(length=100), nullable=True),
    sa.Column('body_colour', sa.String(length=50), nullable=True),
    sa.Column('front_image', sa.String(length=255), nullable=True),
    sa.Column('rear_image', sa.String(length=255), nullable=True),
    sa.Column('left_image', sa.String(length=255), nullable=True),
    sa.Column('right_image', sa.String(length=255), nullable=True),
    sa.Column('glb_file', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id')
    )
    op.create_index(op.f('ix_device_models_id'), 'device_models', ['id'], unique=False)
    op.create_table('device_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_device_types_id'), 'device_types', ['id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vendors_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_device_types_id'), table_name='device_types')
    op.drop_table('device_types')
    op.drop_index(op.f('ix_device_models_id'), table_name='device_models')
    op.drop_table('device_models')
    # ### end Alembic commands ###
