"""update device model

Revision ID: c57245e158fd
Revises: bd1bb7189838
Create Date: 2026-07-30 08:49:18.743490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c57245e158fd'
down_revision: Union[str, Sequence[str], None] = 'bd1bb7189838'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_models', sa.Column('device_type_id', sa.Integer(), nullable=False))
    op.add_column('device_models', sa.Column('vendor_id', sa.Integer(), nullable=False))
    op.add_column('device_models', sa.Column('top_image', sa.String(length=255), nullable=True))
    op.add_column('device_models', sa.Column('bottom_image', sa.String(length=255), nullable=True))
    op.add_column('device_models', sa.Column('glb_path', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'device_models', 'vendors', ['vendor_id'], ['id'])
    op.create_foreign_key(None, 'device_models', 'device_types', ['device_type_id'], ['id'])
    op.drop_column('device_models', 'glb_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_models', sa.Column('glb_file', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'device_models', type_='foreignkey')
    op.drop_constraint(None, 'device_models', type_='foreignkey')
    op.drop_column('device_models', 'glb_path')
    op.drop_column('device_models', 'bottom_image')
    op.drop_column('device_models', 'top_image')
    op.drop_column('device_models', 'vendor_id')
    op.drop_column('device_models', 'device_type_id')
    # ### end Alembic commands ###
